import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import {Segment, Button,Header,Label,Sticky,Grid,Container, Card} from 'semantic-ui-react'
import {client} from '../utils/shopify'
import styles from '../styles/Home.module.css'

export default function Home({products}) {

  return (
    <Container className={styles.container} textAlign='center'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<br></br>
    
      <Card.Group itemsPerRow={3}>
      {products.map((product) => {
          return(
            <Link href={`/product/${product.handle}`}>
              <Card>
                <Image src={product.images[0].src}  width={500} height={500} />
                <Card.Content>

                <Header as="h3">{product.title}</Header>
                <span>{product.variants[0].price}</span>
                </Card.Content>
              </Card>
            </Link>
          );
        })}

</Card.Group>

     </Container>
  )
}




export async function getServerSideProps(context) {
  
  const collectionId = 'Z2lkOi8vc2hvcGlmeS9Db2xsZWN0aW9uLzI2ODA1MTcxMDEyMA==';
  // Set a parameter for first x products, defaults to 20 if you don't provide a param
  
  const collections = await client.collection.fetchWithProducts(collectionId, {productsFirst:9});
  const products = await collections.products;


  // const collections = await client.collection.fetchWithProducts(collectionId, {productsFirst: 10}).then((collection) => {
  //   // Do something with the collection
  //   console.log(collection);
  //   console.log(collection.products);
  // });



  return {
    props: {
    
      collections: JSON.parse(JSON.stringify(collections)),
      products : JSON.parse(JSON.stringify(products)),
      
    }, // will be passed to the page component as props
  }
}


